In [1]:
import numpy as np
arr=np.random.random((10,1))
print(arr)
m=np.mean(arr)
print(m)

[[0.90752185]
 [0.73010763]
 [0.98868639]
 [0.34716281]
 [0.83337284]
 [0.43261777]
 [0.5031661 ]
 [0.81644512]
 [0.53648495]
 [0.14905144]]
0.6244616903959546


In [2]:
import numpy as np
arr=np.random.random((20,1))
print(arr)
sd=np.std(arr)
print("Standard Deviation:", sd)
print("Variance:",sd*sd)

[[0.99719208]
 [0.80491023]
 [0.44819637]
 [0.4490551 ]
 [0.96866411]
 [0.65002332]
 [0.26190888]
 [0.60598988]
 [0.16743019]
 [0.37167336]
 [0.55742392]
 [0.94441702]
 [0.43302962]
 [0.25545207]
 [0.74846988]
 [0.05929928]
 [0.97391023]
 [0.63631265]
 [0.92856158]
 [0.64545521]]
Standard Deviation: 0.2801545413984871
Variance: 0.07848656706619662


In [3]:
import numpy as np
A=np.random.random((10,20))
B=np.random.random((20,25))
C=np.matmul(A,B)
print(C)
print("Sum of elements of C:",np.sum(C))

[[5.04654152 4.36671923 4.50660727 5.55956746 5.28797138 5.32547281
  6.41577865 6.01694555 5.48588883 4.24985568 5.20228918 4.21234028
  5.84671558 5.10301173 4.66173472 2.63302037 5.69542087 5.207649
  6.4271352  6.30685464 4.22919829 4.99860037 5.13600313 5.09371227
  5.1747811 ]
 [3.63959784 4.22070927 3.83892417 4.07596257 4.66993561 5.00077636
  4.63849942 4.42542921 4.24715715 3.90431697 4.46146519 3.63888903
  4.54441302 3.74408361 3.80655185 2.1201511  4.46749013 3.58282307
  4.46268548 4.37431893 4.0022121  3.95688472 4.26884787 4.49958584
  3.74606549]
 [4.11845265 4.45470353 4.44809239 4.74619239 5.39801058 5.43673302
  5.21894999 5.04600633 4.91443718 4.2802049  4.86228603 4.19033958
  5.05429037 4.54753415 4.58680676 2.86053709 5.0032122  4.66451877
  5.18298212 5.65940476 4.39767297 4.60431057 4.92873468 5.25005531
  4.37593827]
 [5.41315908 5.20602945 4.64287562 5.45242303 5.35899756 5.89257039
  6.94769697 5.91297556 5.87716054 4.97220424 5.35666425 5.43042715
  5.7050

In [4]:
import numpy as np
A=np.random.random((10,1))
print(A)
def func(y):
     return (1 / (1 + np.exp(-y)))

res = np.apply_along_axis(func, 0, A)

print('*'*50)

print(res)

[[0.43624824]
 [0.81475872]
 [0.26513261]
 [0.73823706]
 [0.89707356]
 [0.53666471]
 [0.40232549]
 [0.7394793 ]
 [0.78442477]
 [0.01815638]]
**************************************************
[[0.6073647 ]
 [0.69312263]
 [0.56589758]
 [0.67661023]
 [0.71034775]
 [0.6310362 ]
 [0.59924626]
 [0.67688198]
 [0.68663297]
 [0.50453897]]
